---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  labels:
    elastic-app: elasticsearch-logging
    role: data
  name: elasticsearch-logging
  namespace: default
spec:
  replicas: 1
  serviceName: elasticsearch-logging
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      elastic-app: elasticsearch-logging
  template:
    metadata:
      labels:
        elastic-app: elasticsearch-logging
        role: data
    spec:
      containers:
        - name: elasticsearch-data
          image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
          ports:
            - containerPort: 9200
              protocol: TCP
            - containerPort: 9300
              protocol: TCP
          volumeMounts:
            - name: esdata
              mountPath: /usr/share/elasticsearch/data
          env:
            - name: "cluster.name"
              value: "elasticsearch-cluster"
            - name: "discovery.zen.ping.unicast.hosts"
              value: "elasticsearch-logging"
            - name: "node.master"
              value: "false"
            - name: "node.data"
              value: "true"
            - name: "ES_JAVA_OPTS"
              value: "-Xms256m -Xmx256m"
              #    securityContext:
              #      privileged: true
      volumes:
        - name: esdata
          emptyDir: {}
      # serviceAccountName: elasticsearch-logging
      #  tolerations:
      #  - key: node-role.kubernetes.io/master
      #    effect: NoSchedule

---
kind: Service
apiVersion: v1
metadata:
  labels:
    elastic-app: elasticsearch-logging
  name: elasticsearch-logging
  namespace: default
spec:
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: 32242
  selector:
    elastic-app: elasticsearch-logging
  type: NodePort
